# Generated by Django 5.0.6 on 2024-06-02 10:02

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_customuser_options_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", account.models.CustomUserManager()),
            ],
        ),
    ]
