# Generated by Django 5.0.6 on 2024-06-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_customuser_is_staff_alter_customuser_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediator",
            name="docs",
            field=models.FileField(blank=True, null=True, upload_to="lawyer_docs/"),
        ),
    ]
